name: Python package

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    
          
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Conda info
        shell: bash -el {0}
          run: conda info


        
        